### ISSUE TITLE
Compilation issue

### ISSUE THREAD

**Issue by pascalangst** [0x002A/MuCHSALSA#14]
Dear all,

I'm facing an issue during compilation:

```
[ 62%] Linking CXX executable bin/muchsalsa
CMakeFiles/muchsalsa.dir/src/main.cpp.o: In function `ceil(float)':
main.cpp:(.text._Z4ceilf[_Z4ceilf]+0x13): undefined reference to `ceilf'
bin/libms.a(ap.cpp.o): In function `(anonymous namespace)::getSequenceBetweenAnchors(muchsalsa::matching::MatchMap const&, muchsalsa::SequenceAccessor&, unsigned int, unsigned int, unsigned int, std::__1::pair<int, int> const&, std::__1::pair<int, int> const&, muchsalsa::Toggle)':
ap.cpp:(.text+0xea63): undefined reference to `floor'
ap.cpp:(.text+0xeb4c): undefined reference to `floor'
ap.cpp:(.text+0xec0e): undefined reference to `floor'
ap.cpp:(.text+0xf194): undefined reference to `floor'
ap.cpp:(.text+0xf283): undefined reference to `floor'
bin/libms.a(ap.cpp.o):ap.cpp:(.text+0xf354): more undefined references to `floor' follow
clang-15: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [CMakeFiles/muchsalsa.dir/build.make:152: bin/muchsalsa] Error 1
make[1]: *** [CMakeFiles/Makefile2:172: CMakeFiles/muchsalsa.dir/all] Error 2
make: *** [Makefile:146: all] Error 2
```

Please let me know what I can provide to make the troubleshooting easier.

Thank you,
Pascal

**Comment by 0x002A** [comment]
Actually this is a linker error and not a compilation issue. It seems that the linker cannot find a definition for ceilf. 

Are you sure that you have libc++ installed on your system?

In the meantime you can use the prebuilt version of MuCHSALSA provided through the releases page.

Cheers,
Kevin

**Comment by pascalangst** [comment]
Hi Kevin,

Thank you for the quick response!

1) I just saw that in my LLVM, libc++-15 is probably not included, but libc++-14. Maybe that's what causing the error?
2) The prebuilt release "[Nightly Build](https://github.com/0x002A/MuCHSALSA/releases/tag/nightly)" is not working for me. How was it compressed?
3) The prebuilt release "[0.0.2](https://github.com/0x002A/MuCHSALSA/releases/tag/0.0.2)" seems to work for me. I'll use this one in the meantime.

Cheers,
Pascal

**Comment by 0x002A** [comment]
Regarding 1:

Interesting. Did you change the CMakeLists-file to use clang++-14 then or just compiled with the older version of LLVM right away?

Regarding 2:
I would love if you'd report an issue with the exact error message you're getting from the nightly. The nightly is not compressed in any way, the file you can download for this release is the executable you can replace the executable in your pipeline with. So you'd normally download version 0.0.2, extract the folder, download the nightly muchsalsa-file and replace the binary of 0.0.2 with it.

Regarding 3:
Glad to hear that version 0.0.2 is working for you.

Cheers,
Kevin

**Comment by pascalangst** [comment]
It was not clear to me that we can just replace the binary. It works the way you described.
Thanks,
Pascal

**Comment by 0x002A** [comment]
Good that it works now.

If you still want support with your linker errors let me know.

Otherwise feel free to close this issue.

Thanks,
Kevin

**Comment by pascalangst** [comment]
Thank you for your support, Kevin!
