### ISSUE TITLE
add MuCHSALSA to bioconda cloud

### ISSUE THREAD

**Issue by xiekunwhy** [0x002A/MuCHSALSA#15]
Hi,

Would you please add MuCHSALSA to bioconda cloud, I have no root permission and feel hard to compile it.

Best,
Kun

**Comment by 0x002A** [comment]
Hey Kun,

you can download a pre-compiled version from the releases page.

How about that?

Cheers,
Kevin

**Comment by 0x002A** [comment]
Closing the issue because of no further comment. Open a new issue in case you need further assistance.

Cheers,
Kevin
